apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  labels:
    app: curl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - image: docker.io/rancher/curl
        command:
          - sleep
          - "8640000"
        imagePullPolicy: IfNotPresent
        name: curl
      restartPolicy: Always